name: Build and deploy Node.js app to Azure Web App - forum-backend-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install backend dependencies
        run: npm install

      - name: Zip backend (exclude frontend and hidden files)
        run: |
          zip -r release.zip . \
            -x "client/*" \
            -x "client/**" \
            -x ".git*" \
            -x ".github/*" \
            -x "node_modules/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-backend
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-backend

      - name: Unzip
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BA256DE2E5C04E289818E0192CDD4524 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_735951A89EC04806BDF0E8560AC3D25F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DEDE616145544C27AC52946AF63A8E67 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'forum-backend-api'
          slot-name: 'Production'
          package: .
